### ISSUE TITLE
The path to Forestry 5 (MC 1.9)

### ISSUE THREAD

**Issue by Nedelosk** [ForestryMC/ForestryMC#1091]
- [x] Fix Sync problems at all blocks (#1094, #1095)
- [x] Fix wrong leave item color (#1082)
- [X] Fix sapling proplem (#1103)
- [X] Fix wrong item name from hive items
- [X] Add IItemHandler capability to all things with inventory (#1106)
- [X] Improve IItemHandler Integreation (#1112)
- [X] Add a Greenhouse Multiblock (#442)
- [X] Improve Greenhouse Multiblock
- [X] Improve the butterfly system
- [x] Add water particles to the greenhouse sprinkler.

**Comment by Nedelosk** [comment]
@mezz You can add more when you want .

**Comment by mezz** [comment]
:+1:

**Comment by hea3ven** [comment]
Maybe, to consider: Add IItemHandler capability to the backpacks?

**Comment by Nedelosk** [comment]
For what is the IItemHandler ?

**Comment by mezz** [comment]
The new forge "capabilities" can work on tile entities and items. They have a better interface than ISidedInventory and IInventory, so we should use them.

**Comment by CovertJaguar** [comment]
@mezz See #1106 for hints on how to achieve full IItemHandler support for the entire mod with a minimum of work.

**Comment by CovertJaguar** [comment]
Railcraft now has the backbone of IItemHandler support. Take what you need: https://github.com/CovertJaguar/Railcraft/commit/0ac2a4e81abd6a49cb3129999ff4d5a3e629c4eb
https://github.com/CovertJaguar/Railcraft/commit/b748a7325b170066f732cbb0f28b8cfdab38a06d

Should be a simple drop in replacement for the Manipulators and Iterators, though you'll need to give some thought to how you actually acquire IItemHandler objects. I haven't finalized that part, but the code can now manipulate them transparently. All untested of course. ;)

**Comment by CovertJaguar** [comment]
Looks good! 

But do keep in mind that IItemHandler does not extend IInventory. You will need to acquire the IItemHandler object and pass it to the Manipulator/Iterators to fully complete support. You might find [InventoryObject](https://github.com/ForestryMC/ForestryMC/blob/Greenhouse/src/main/java/forestry/core/inventory/InventoryObject.java) a useful container for either type of inventory object. Combine it with some kind of getter function (InventoryObject getInventory(World, BlockPos, EnumFacing))

**Comment by Nedelosk** [comment]
## The new butterfly cocoons:

![2016-03-26_11 24 51](https://cloud.githubusercontent.com/assets/10259214/14059566/6056dd6e-f345-11e5-8d9e-5b7493b3cdd3.png)

**Comment by rcistano** [comment]
where can we get the mod for 1.8 +

**Comment by mezz** [comment]
We're still working on some things before it is released publicly. I think we will be ready as an alpha version some time soon.

**Comment by mezz** [comment]
@Nedelosk can you add an item for the cocoon?

**Comment by mezz** [comment]
Closing this, we can use the milestone and individual issues for anything else.
