### ISSUE TITLE
Plans for the future

### ISSUE THREAD

**Issue by Nedelosk** [ForestryMC/ForestryMC#1745]
These are my plans for the future of forestry and what I have currently planned to do in the next time.
- [ ] The Greenhouse #1668 
   - [x] Finishing the rework #1780
   - [ ] Writing a greenhouse [wiki page](https://forestryforminecraft.info/breeding:greenhouse)
   - [ ] Find people to test the new greenhouse
   - [ ] Fixing bugs
   - [x] Port the rework to 1.12
- [x] Fixing old bugs
- [x] Farming support Forestry 5 #1471 
   - [x] Fix Extra Utilities 2 and Natura support
   - [x] Add farm support for more mods
   - [x] Improve Fertilizer Config #1717
   - [x] Port the mod support to 1.12
- [x] Break up the modules
- [x] Working on the genetic api
  - [x] Working on a new bee / tree / butterfly chest #954

**Comment by Kris1432** [comment]
If you need the new greenhouse testing just hit me up!

**Comment by Nedelosk** [comment]
@Kris1432, @whitestarx0312, @temp1011, @mezz, @KorDum  What do you think about the new database block ?
Its a chest that can contain every item with genetic information like bees, trees butterflies and flowers.
The chest has 136 slots. The gui has a searchbar and it has a small analyzer section at the left side with four tabs.
1. All active alleles
2. All inaktive alleles
3. The products of the active species
4. All possible mutations of the active species and the mutations that has the active species as resulute.
![2017-11-02_16 44 14](https://user-images.githubusercontent.com/10259214/34615171-35307ace-f234-11e7-9781-e251121e78d6.png)
![2018-01-05_16 19 08](https://user-images.githubusercontent.com/10259214/34615172-354ec722-f234-11e7-947b-6866020b9e13.png)
![2018-01-05_16 19 13](https://user-images.githubusercontent.com/10259214/34615173-356fae60-f234-11e7-9523-7db75f7cbb8f.png)
![2018-01-05_16 26 44](https://user-images.githubusercontent.com/10259214/34615492-5fd3d52c-f235-11e7-82fe-8da594bfb889.png)
![2018-01-05_16 27 02](https://user-images.githubusercontent.com/10259214/34615479-56278d34-f235-11e7-9a38-97bf3e3392c5.png)

**Comment by KorDum** [comment]
Instead Arborist's/etc chests? Those chests will become useless, right? — 125 slots and without info, search and analyzer functional.

**Comment by temp1011** [comment]
Chests will probably be cheaper I imagine

**Comment by KorDum** [comment]
Cost of recipe should be too many "expensive", otherwise nobody will use ordinary chests, because Database block is more convenient to use, judging by screenshots above.

@Nedelosk How can I select individual without put out? One click for select and two click for put out?

**Comment by Nedelosk** [comment]
@KorDum You can select a slot with the arrow keys or with a mouse click and the ctrl key pressed down.

**Comment by KorDum** [comment]
It seems like very usable, but the main doubt about the ease of craft a block (now the recipe is simple).
This block is a killerfeature, do not you think so?

**Comment by temp1011** [comment]
Maybe make it require an analyser and some kind of forestry chest in recipe? Might help with balance ( analyser requires diamond but this doesn't ATM)

**Comment by KorDum** [comment]
maybe?
> [
>     [Bronze ingot, Portable Analyzer, Bronze ingot],
>     [Arborist's chest, Sturdy Casing, Lepidopterist's chest],
>     [planks, Apiarist's chest, planks]
> ]

And vanilla chest if some modules are disabled (some chests in recipes doesn't exists).

**Comment by Nedelosk** [comment]
I think two different genetic chests are enough, or not ?

**Comment by Nedelosk** [comment]
maybe?
> [
>     [Bronze ingot, Portable Analyzer, Bronze ingot],
>     [Arborist's chest, Sturdy Casing, Lepidopterist's chest],
>     [planks, Apiarist's chest, planks]
> ]

**Comment by KorDum** [comment]
Could be so. Then the third chest replaced with Royal Jelly. To make the block after crossing the bees (if module is enabled).

**Comment by KorDum** [comment]
Thus, you can "delay" crafting of block from the beginning of the game.

**Comment by KorDum** [comment]
> [
> [Bronze ingot, Portable Analyzer, Bronze ingot],
> [*rist's chest, Sturdy Casing, *rist's chest],
> [planks, Royal Jelly, planks]
> ]

?

**Comment by temp1011** [comment]
Seems a bit harsh if you only like trees and butterflies :)

**Comment by Nedelosk** [comment]
What about a plum as the equivalent of Royal Jelly ?

**Comment by KorDum** [comment]
Yes, Royal Jelly => some another item (like vanilla chest?), if module is disabled, maybe?

**Comment by KorDum** [comment]
Or plum, yes.

**Comment by Nedelosk** [comment]
[
[Bronze ingot, Portable Analyzer, Bronze ingot],
[*rist's chest, Sturdy Casing, *rist's chest],
[planks, Royal Jelly / Plum / (vanilla chest), planks]
]
?

**Comment by jjc54** [comment]
I think this is an excellent replacement for the forestry chests!

**Comment by KorDum** [comment]
> The Greenhouse #1668
>  Find people to test the new greenhouse

I'm currently actively looking at this design and have already noticed one more bug related to loading chunks. But so far it has not been possible to stabilize its appearance...
